version: 2

before:
  hooks:
    - git submodule update --init --recursive
    - go mod tidy

builds:
  - id: observer-cli
    main: ./cmd/observer
    binary: observer
    goos:   [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.cliVersion={{.Version}}

archives:
  - id: observer-cli
    builds: [observer-cli]
    name_template: "observer-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
