package scanner

import "regexp"

// BuiltInRules returns the complete set of built-in detection rules for
// quantum-vulnerable cryptographic algorithms across all supported languages.
// All patterns are compiled at startup and panic on invalid regex (a programming error).
func BuiltInRules() []Rule {
	return []Rule{
		// ── Java ──────────────────────────────────────────────────────────────

		{
			ID:        "java-rsa-keygen",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)KeyPairGenerator\.getInstance\s*\(\s*["']RSA["']`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "RSA key generation detected. RSA is vulnerable to Shor's algorithm on quantum computers.",
			Migration:  "Replace with CRYSTALS-Kyber (FIPS 203) for key encapsulation or CRYSTALS-Dilithium (FIPS 204) for signatures.",
		},
		{
			ID:        "java-rsa-cipher",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)Cipher\.getInstance\s*\(\s*["']RSA`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "RSA cipher instantiation detected. RSA encryption is quantum-vulnerable.",
			Migration:  "Replace with CRYSTALS-Kyber (ML-KEM, FIPS 203) for asymmetric encryption.",
		},
		{
			ID:        "java-ecdh-agreement",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)KeyAgreement\.getInstance\s*\(\s*["']ECDH["']`),
			Algorithm: "ECDH",
			Severity:  SeverityHigh,
			Message:   "ECDH key agreement detected. Elliptic-curve Diffie-Hellman is broken by Shor's algorithm.",
			Migration:  "Replace with CRYSTALS-Kyber (ML-KEM, FIPS 203) for key encapsulation.",
		},
		{
			ID:        "java-ec-keygen",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)KeyPairGenerator\.getInstance\s*\(\s*["']EC["']`),
			Algorithm: "ECDSA",
			Severity:  SeverityHigh,
			Message:   "Elliptic-curve key generation detected. EC keys are quantum-vulnerable.",
			Migration:  "Replace with CRYSTALS-Dilithium (ML-DSA, FIPS 204) for digital signatures.",
		},
		{
			ID:        "java-sha1-sig",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)Signature\.getInstance\s*\(\s*["']SHA1with`),
			Algorithm: "SHA1withRSA/ECDSA",
			Severity:  SeverityCritical,
			Message:   "SHA-1 based signature scheme detected. SHA-1 is cryptographically broken and the underlying asymmetric primitive is also quantum-vulnerable.",
			Migration:  "Replace immediately with CRYSTALS-Dilithium (FIPS 204). SHA-1 is deprecated by NIST.",
		},
		{
			ID:        "java-dsa-keygen",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)KeyPairGenerator\.getInstance\s*\(\s*["']DSA["']`),
			Algorithm: "DSA",
			Severity:  SeverityHigh,
			Message:   "DSA key generation detected. DSA is vulnerable to Shor's algorithm.",
			Migration:  "Replace with CRYSTALS-Dilithium (ML-DSA, FIPS 204) for digital signatures.",
		},
		{
			ID:        "java-dh-keygen",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)KeyPairGenerator\.getInstance\s*\(\s*["']DH["']`),
			Algorithm: "DH",
			Severity:  SeverityHigh,
			Message:   "Diffie-Hellman key generation detected. DH is vulnerable to Shor's algorithm.",
			Migration:  "Replace with CRYSTALS-Kyber (ML-KEM, FIPS 203) for key encapsulation.",
		},
		{
			ID:        "java-bc-rsa-params",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)RSAKeyGenerationParameters|RSAPrivateCrtKeyParameters`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "Bouncy Castle RSA key parameter class detected. RSA is quantum-vulnerable.",
			Migration:  "Replace with Bouncy Castle's post-quantum KEM classes or CRYSTALS-Kyber (FIPS 203).",
		},
		{
			ID:        "java-bc-ecdh",
			Language:  "java",
			Pattern:   regexp.MustCompile(`(?i)ECDHBasicAgreement|ECDHCBasicAgreement`),
			Algorithm: "ECDH",
			Severity:  SeverityHigh,
			Message:   "Bouncy Castle ECDH agreement class detected. ECDH is quantum-vulnerable.",
			Migration:  "Replace with Bouncy Castle's CRYSTALS-Kyber implementation (FIPS 203).",
		},

		// ── Python ────────────────────────────────────────────────────────────

		{
			ID:        "python-rsa-generate",
			Language:  "python",
			Pattern:   regexp.MustCompile(`(?i)rsa\.generate_private_key|RSA\.generate|generate_private_key.*rsa`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "RSA private key generation detected. RSA is vulnerable to Shor's algorithm.",
			Migration:  "Replace with kyber-py or the cryptography library's post-quantum primitives (FIPS 203/204).",
		},
		{
			ID:        "python-ec-generate",
			Language:  "python",
			Pattern:   regexp.MustCompile(`(?i)ec\.generate_private_key|ECDH\(|ECDSA\(`),
			Algorithm: "ECDSA/ECDH",
			Severity:  SeverityHigh,
			Message:   "Elliptic-curve key generation or agreement detected. EC primitives are quantum-vulnerable.",
			Migration:  "Replace with ML-KEM (FIPS 203) for key encapsulation or ML-DSA (FIPS 204) for signatures.",
		},
		{
			ID:        "python-rsa-import",
			Language:  "python",
			Pattern:   regexp.MustCompile(`(?i)from cryptography.*import.*RSA|import rsa\b`),
			Algorithm: "RSA",
			Severity:  SeverityMedium,
			Message:   "RSA module import detected. Verify usage is not in a key-exchange or signing path.",
			Migration:  "Audit all usages and replace quantum-vulnerable operations with FIPS 203/204 equivalents.",
		},
		{
			ID:        "python-paramiko-rsa",
			Language:  "python",
			Pattern:   regexp.MustCompile(`(?i)paramiko\.RSAKey|RSAKey\.generate`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "Paramiko RSA key usage detected. SSH RSA keys are quantum-vulnerable.",
			Migration:  "Migrate SSH infrastructure to use Ed25519 in the short term; plan for post-quantum SSH once RFC 9409 implementations mature.",
		},
		{
			ID:        "python-pycrypto-rsa",
			Language:  "python",
			Pattern:   regexp.MustCompile(`(?i)from Crypto\.PublicKey import RSA|Crypto\.PublicKey\.RSA`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "PyCryptodome RSA import detected. RSA is quantum-vulnerable.",
			Migration:  "Replace with post-quantum key encapsulation (ML-KEM) or signature (ML-DSA) schemes.",
		},

		// ── Go ────────────────────────────────────────────────────────────────

		{
			ID:        "go-rsa-generate",
			Language:  "go",
			Pattern:   regexp.MustCompile(`(?i)rsa\.GenerateKey|rsa\.GenerateMultiPrimeKey`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "Go RSA key generation detected. RSA is vulnerable to Shor's algorithm.",
			Migration:  "Replace with golang.org/x/crypto post-quantum primitives or the circl library (CRYSTALS-Kyber/Dilithium).",
		},
		{
			ID:        "go-ecdh",
			Language:  "go",
			Pattern:   regexp.MustCompile(`(?i)ecdh\.P256\(\)|ecdh\.P384\(\)|ecdh\.P521\(\)|ecdh\.X25519\(\)`),
			Algorithm: "ECDH",
			Severity:  SeverityHigh,
			Message:   "Go ECDH curve instantiation detected. All standard ECDH curves are quantum-vulnerable.",
			Migration:  "Replace with CRYSTALS-Kyber (ML-KEM, FIPS 203) via the Cloudflare CIRCL library.",
		},
		{
			ID:        "go-ecdsa",
			Language:  "go",
			Pattern:   regexp.MustCompile(`(?i)ecdsa\.GenerateKey|ecdsa\.Sign|ecdsa\.Verify`),
			Algorithm: "ECDSA",
			Severity:  SeverityHigh,
			Message:   "Go ECDSA operation detected. ECDSA is vulnerable to Shor's algorithm.",
			Migration:  "Replace with CRYSTALS-Dilithium (ML-DSA, FIPS 204) via the Cloudflare CIRCL library.",
		},
		{
			ID:        "go-dsa",
			Language:  "go",
			Pattern:   regexp.MustCompile(`(?i)dsa\.GenerateKey|dsa\.Sign`),
			Algorithm: "DSA",
			Severity:  SeverityCritical,
			Message:   "Go DSA operation detected. DSA is deprecated and quantum-vulnerable.",
			Migration:  "Replace with CRYSTALS-Dilithium (ML-DSA, FIPS 204). DSA has been retired by NIST.",
		},
		{
			ID:        "go-tls-rsa-cipher",
			Language:  "go",
			Pattern:   regexp.MustCompile(`(?i)tls\.TLS_RSA_WITH|tls\.TLS_ECDHE_RSA`),
			Algorithm: "RSA/ECDHE-RSA",
			Severity:  SeverityMedium,
			Message:   "TLS cipher suite with RSA key exchange detected. These suites are quantum-vulnerable.",
			Migration:  "Migrate to TLS 1.3 with post-quantum key exchange (e.g., X25519Kyber768) once widely supported.",
		},

		// ── JavaScript / TypeScript ───────────────────────────────────────────

		{
			ID:        "js-webcrypto-rsa-ec",
			Language:  "javascript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.subtle\.generateKey.*["'](RSA|EC)`),
			Algorithm: "RSA/EC",
			Severity:  SeverityHigh,
			Message:   "Web Crypto API RSA or EC key generation detected. These algorithms are quantum-vulnerable.",
			Migration:  "Plan migration to post-quantum primitives when WebCrypto adds ML-KEM/ML-DSA support.",
		},
		{
			ID:        "ts-webcrypto-rsa-ec",
			Language:  "typescript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.subtle\.generateKey.*["'](RSA|EC)`),
			Algorithm: "RSA/EC",
			Severity:  SeverityHigh,
			Message:   "Web Crypto API RSA or EC key generation detected. These algorithms are quantum-vulnerable.",
			Migration:  "Plan migration to post-quantum primitives when WebCrypto adds ML-KEM/ML-DSA support.",
		},
		{
			ID:        "js-jose-jwt",
			Language:  "javascript",
			Pattern:   regexp.MustCompile(`(?i)new SignJWT|jose\.jwtSign`),
			Algorithm: "RSA/EC (JWT)",
			Severity:  SeverityMedium,
			Message:   "JOSE/JWT signing detected. RS256/ES256 algorithms rely on quantum-vulnerable primitives.",
			Migration:  "Audit the JWT algorithm in use. Plan migration to post-quantum signature schemes.",
		},
		{
			ID:        "ts-jose-jwt",
			Language:  "typescript",
			Pattern:   regexp.MustCompile(`(?i)new SignJWT|jose\.jwtSign`),
			Algorithm: "RSA/EC (JWT)",
			Severity:  SeverityMedium,
			Message:   "JOSE/JWT signing detected. RS256/ES256 algorithms rely on quantum-vulnerable primitives.",
			Migration:  "Audit the JWT algorithm in use. Plan migration to post-quantum signature schemes.",
		},
		{
			ID:        "js-node-crypto-rsa",
			Language:  "javascript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.generateKeyPair\s*\(\s*['"]rsa['"]`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "Node.js crypto RSA key pair generation detected. RSA is quantum-vulnerable.",
			Migration:  "Replace with post-quantum KEM (ML-KEM, FIPS 203) once Node.js gains support, or use a WASM shim.",
		},
		{
			ID:        "ts-node-crypto-rsa",
			Language:  "typescript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.generateKeyPair\s*\(\s*['"]rsa['"]`),
			Algorithm: "RSA",
			Severity:  SeverityHigh,
			Message:   "Node.js crypto RSA key pair generation detected. RSA is quantum-vulnerable.",
			Migration:  "Replace with post-quantum KEM (ML-KEM, FIPS 203) once Node.js gains support, or use a WASM shim.",
		},
		{
			ID:        "js-node-crypto-ec",
			Language:  "javascript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.generateKeyPair\s*\(\s*['"]ec['"]`),
			Algorithm: "ECDSA/ECDH",
			Severity:  SeverityHigh,
			Message:   "Node.js crypto EC key pair generation detected. EC primitives are quantum-vulnerable.",
			Migration:  "Replace with ML-KEM (FIPS 203) for key encapsulation or ML-DSA (FIPS 204) for signatures.",
		},
		{
			ID:        "ts-node-crypto-ec",
			Language:  "typescript",
			Pattern:   regexp.MustCompile(`(?i)crypto\.generateKeyPair\s*\(\s*['"]ec['"]`),
			Algorithm: "ECDSA/ECDH",
			Severity:  SeverityHigh,
			Message:   "Node.js crypto EC key pair generation detected. EC primitives are quantum-vulnerable.",
			Migration:  "Replace with ML-KEM (FIPS 203) for key encapsulation or ML-DSA (FIPS 204) for signatures.",
		},
	}
}
